import TikTok from "@/Shared/Icon/Icons/TikTok"
import Instagram from "@/Shared/Icon/Icons/Instagram"
import Youtube from "@/Shared/Icon/Icons/Youtube"
import Linkedin from "@/Shared/Icon/Icons/Linkedin"
import Spotify from "@/Shared/Icon/Icons/Spotify"
import Info from "@/Shared/Icon/Icons/Info"
import ClosedEye from "@/Shared/Icon/Icons/ClosedEye"
import Eye from "@/Shared/Icon/Icons/Eye"
import ArrowChervonRight from '@/Shared/Icon/Icons/ArrowChervonRight'
import ArrowChervonLeft from '@/Shared/Icon/Icons/ArrowChervonLeft'
import Currency from '@/Shared/Icon/Icons/Currency'
import Options from '@/Shared/Icon/Icons/Options'
import Gear from '@/Shared/Icon/Icons/Gear'

export { default as UserIcon } from './UserIcon'
export { default as Calendar03Icon } from './Calendar03Icon'
export { default as AddCircleIcon } from './AddCircleIcon'
export { default as Home09Icon } from './Home09Icon'
export { default as CalendarAdd01Icon } from './CalendarAdd01Icon'
export { default as Wrench01Icon } from './Wrench01Icon'
export { default as UserGroup03Icon } from './UserGroup03Icon'
export { default as Location03Icon } from './Location03Icon'
export { default as Cancel01Icon } from './Cancel01Icon'
export { default as CheckIcon } from './CheckIcon'
export { default as SquareLock02Icon } from './SquareLock02Icon'
export { default as GoogleIcon } from './GoogleIcon'
export { default as SquareLock01Icon } from './SquareLock01Icon'
export { default as ScratchCardIcon } from './ScratchCardIcon'
export { default as PenTool03 } from './PenTool03'
export { default as WhatsappIcon } from './WhatsappIcon'
export { default as StarIcon } from './StarIcon'
export { default as Share01Icon } from './Share01Icon'
export { default as LogoutSquare02Icon } from './LogoutSquare02Icon'
export { default as ArrowUpLeft01Icon } from './ArrowUpLeft01Icon'
export { default as Camera01Icon } from './Camera01Icon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as Mail01Icon } from './Mail01Icon'
export { default as Call02Icon } from './Call02Icon'
export { default as PencilEdit02Icon } from './PencilEdit02Icon'
export { default as ViewIcon } from './ViewIcon'
export { default as ViewOffSlashIcon } from './ViewOffSlashIcon'
export { default as Clock05Icon } from './Clock05Icon'
export { default as Undo03Icon } from './Undo03Icon'
export { default as ArrowLeft02Icon } from './ArrowLeft02Icon'
export { default as SimcardDualIcon } from './SimcardDualIcon'
export { default as Moon02Icon } from './Moon02Icon'
export { default as Sun01Icon } from './Sun01Icon'
export { default as SentIcon } from './SentIcon'
export { default as Delete02Icon } from './Delete02Icon'
export { default as MoreVerticalCircle01Icon } from './MoreVerticalCircle01Icon'
export { default as Comment01Icon } from './Comment01Icon'
export { default as FavouriteIcon } from './FavouriteIcon'
export { default as NotificationIcon } from './NotificationIcon'
export { default as CarIcon } from './CarIcon'
export { default as ScissorIcon } from './ScissorIcon'
export { default as WifiIcon } from './WifiIcon'
export { default as ColdIcon } from './ColdICon'
export { default as CustomerService01Icon } from './CustomerService01Icon'
export { default as ChairBarberIcon } from './ChairBarberIcon'
export { default as PaintBrush01Icon } from './PaintBrush01Icon'
export { default as Location02Icon } from './Location02Icon'
export { default as FindIcon } from './FindIcon'
export { default as TruckIcon } from './TruckIcon'
export { default as MapsIcon } from './MapsIcon'
export { default as CartIcon } from './CartIcon'
export { default as SaleIcon } from './SaleIcon'
export { default as CrowIcon } from './CrowIcon'
export { default as BrushClockIcon } from './BrushClockIcon'
export { default as EraserIcon } from './EraserIcon'
export { default as Filter } from './Filter'
export { default as Arrow02 } from './Arrow02'
export { default as Control } from './Control'
export { default as TwoArrow } from './TwoArrow'
export { default as ArrowUp } from './ArrowUp'
export { default as ArrowDown } from './ArrowDown'
export { default as ClockUndo } from './ClockUndo'
export { default as Accelerator } from './Accelerator'
export { default as Fuel } from './Fuel'
export { default as Paint } from './Paint'
export { default as ArrowReverse } from './ArrowReverse'
export { default as BusIcon } from './BusIcon'
export { default as Close } from './Close'
export { default as Dollar } from './Dollar'
export { default as PDF } from './PDF'
export { default as UserGroup } from './UserGroup'
export { default as Wallet } from './Wallet'
export { default as Percent } from './Percent'
export { default as lightning } from './lightning'
export { default as TikTok } from './TikTok'
export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Youtube } from './Youtube'
export { default as Linkedin } from './Linkedin'
export { default as Spotify } from './Spotify'
export { default as Info } from './Info'
export { default as ClosedEye } from './ClosedEye'
export { default as Eye } from './Eye'
export { default as Menu } from './Menu'
export { default as ArrowChervonRight } from './ArrowChervonRight'
export { default as ArrowChervonLeft } from './ArrowChervonLeft'
export { default as Currency } from './Currency'
export { default as MobileCode } from './MobileCode'
export { default as Options } from './Options'
export { default as Wrench } from './Wrench'
export { default as Gear } from './Gear'
